[package]
name = "register_routes"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.87", features = ["full"] }
once_cell = "1.20.2"
proc-macro2 = "1.0.89"

[lib]
proc-macro = true